name: Release Please

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    uses: opencoreemr/github-workflows-public/.github/workflows/release-please-reusable.yml@0.0.4
    permissions:
      contents: write
      pull-requests: write
